name: Code Quality & Tests

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: ./.github/actions/setup-uv-project

      - name: Run ruff on Pruna code
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"

      - name: Run mypy on Pruna code
        run: mypy --show-traceback src/pruna

      - name: Run docstring checks with pytest
        run: pytest -m "style"

  test:
    runs-on: pruna-cpu

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/setup-uv-project

      - name: Run tests
        run: |
          pytest -m "cpu and not slow and not high_cpu"
